# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Airports' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Airports
   
  target 'AirportsTests' do
    inherit! :search_paths
    # Pods for testing
use_frameworks!
  end

  target 'AirportsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
